[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting = "6HbAz3WNYGDe2B5wC3WNfYjLZFVHMdw1t3RpiRPAJFRx"

[programs.localnet]
betting = "6HbAz3WNYGDe2B5wC3WNfYjLZFVHMdw1t3RpiRPAJFRx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
initialize = "npx ts-node scripts/initialize.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/betting.ts"
