[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting = "63p9553Ch7gsrAZM1NKq2AYvjybBCZZdpSvynGzUdziC"

[programs.localnet]
betting = "63p9553Ch7gsrAZM1NKq2AYvjybBCZZdpSvynGzUdziC"

[programs.testnet]
betting = "63p9553Ch7gsrAZM1NKq2AYvjybBCZZdpSvynGzUdziC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
initialize = "npx ts-node scripts/initialize.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/betting.ts"
